version: '3.7'
services:
  chatgpt:
    build: .
    image: "chatgpt-command"
    restart: "unless-stopped"
    depends_on:
      - redis
    networks:
      - api-network
    volumes:
      - ./logs:/app/logfile
    environment:
      - DISCORD_API=
      - APPLICATION_ID=
      - GUILD_ID=
      - OPENAI_API=
  redis:
    image: redis
    restart: "unless-stopped"
    ports:
      - "6379:6379"
    networks:
      - api-network
networks:
  api-network:
    driver: bridge
volumes:
  commandlogs: