version: "3.7"
services:
  chatgpt:
    build: .
    image: "chatgpt-command"
    restart: "unless-stopped"
    networks:
      - api-network
    volumes:
      - ./logs:/app/logfile
    environment:
      - DISCORD_API=
      - APPLICATION_ID=
      - GUILD_ID=
      - OPENAI_API=
networks:
  api-network:
    driver: bridge
volumes:
  commandlogs:
